### PR TITLE
Misc tasks to fork

### PR DESCRIPTION
**Pull request by cspotcode**

### CODE REVIEW

**Comment by cspotcode** [comment]
@LironHazan good idea, I don't remember, but I do not think I checked if they were passing in the origin repo.

If you would like to be a collaborator on this repo, let me know and I can add you.  It will give you permission to push to this branch directly.

**Comment by LironHazan** [comment]
@cspotcode thanks, I'll be happy to collaborate, btw in future thinking of modern stack, would we want to use eslint instead of tslint? (TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.)

**Comment by cspotcode** [comment]
`eslint` sounds good to me.  I'm also happy using no linter, only `prettier` and `tsc`.  Either is fine.

I have added you as a collaborator so you should have access to triage issues and pull requests and push code.

**Comment by LironHazan** [comment]
prettier is great, I tend to combine both :) Thanks!

**Comment by LironHazan** [comment]
@cspotcode I've ran the tests in origin branch they passed so I've noticed following commit:
https://github.com/NagRock/ts-mockito/commit/3e51222a6536701af2e3c918728928c7d75c8104
which isn't part of this fork,
I grabbed the diffs and all is green now!

TOTAL: 233 SUCCESS

Finished in 0.729 secs / 0.239 secs @ 21:05:33 GMT+0300 (Israel Daylight Time)

SUMMARY:
✔ 233 tests completed

pushing changes

**Comment by LironHazan** [comment]
@cspotcode sorry to nudge, not sure what happened, the git actions weren't on the fork-tasks local branch so I got them back from upstream/master, I don't see it hooked on commit at the moment

**Comment by cspotcode** [comment]
Awesome, if you think this pull request is ready to merge, go for it.

**Comment by LironHazan** [comment]
@cspotcode sure so I'll merge and will branch out to a "tasks-3" branch which will contain some new configs, wdyt?

**Comment by cspotcode** [comment]
I think we can name the branches according to the changes in them, like `eslint-prettier` if that is what you're changing in that branch.

We may want to postpone large stylistic changes if they make it more difficult to merge existing pull requests from the NagRock and johanblumenthal repositories.

**Comment by LironHazan** [comment]
`eslint-prettier` sounds good, but sure let's have it on a later phase

**Pull request merged**
